@echo off
REM ============================================================
REM  Mp3Tag Tools for DoubleCMD - Windows Installer
REM  Requirements: Python 3, DoubleCMD
REM ============================================================
setlocal enabledelayedexpansion
echo.
echo  =============================================
echo   Mp3Tag Tools for DoubleCMD - Installer
echo  =============================================
echo.

REM ---- Check Python ----
python --version >nul 2>&1
if errorlevel 1 (
    echo ERROR: Python 3 not found in PATH.
    echo Download Python from https://www.python.org/downloads/
    pause & exit /b 1
)
for /f "tokens=*" %%V in ('python --version 2^>^&1') do echo Python: %%V

REM ---- Choose install folder ----
echo.
echo Where do you want to install the scripts?
echo Press ENTER to use the default: %USERPROFILE%\Mp3TagTools
echo Or type a custom path:
set /p INSTALL_DIR="> "
if "%INSTALL_DIR%"=="" set INSTALL_DIR=%USERPROFILE%\Mp3TagTools

echo.
echo Install folder: %INSTALL_DIR%
if not exist "%INSTALL_DIR%" mkdir "%INSTALL_DIR%"

REM ---- Copy scripts ----
echo Copying files...
copy /y "%~dp0tools\id3lib.py"          "%INSTALL_DIR%\id3lib.py"          >nul
copy /y "%~dp0tools\mp3tag_batch.py"    "%INSTALL_DIR%\mp3tag_batch.py"    >nul
copy /y "%~dp0tools\mp3tag_rename.py"   "%INSTALL_DIR%\mp3tag_rename.py"   >nul

REM ---- Create wrapper .bat files via Python ----
REM FIX E: wrapper .bat files are generated by Python instead of a chain of
REM   echo statements, so CMD special characters in INSTALL_DIR cannot corrupt
REM   the generated files.
REM FIX H: strip any trailing backslash from INSTALL_DIR before passing it to
REM   Python. If INSTALL_DIR ends with \ the argument "%INSTALL_DIR%" would
REM   become "C:\Path\" and the C runtime would interpret \" as an escaped
REM   quote, corrupting sys.argv[1]. _D holds the stripped, safe copy.
REM FIX H2: the Python source uses Q=chr(34) instead of \" so the python -c
REM   block contains no literal double-quotes, making CMD argument parsing
REM   formally correct on all inputs.
REM Two %%RANDOM%% values in the temp filename give ~1 billion combinations,
REM making collisions between concurrent instances negligible.

set "_D=%INSTALL_DIR%"
if "%_D:~-1%"=="\" set "_D=%_D:~0,-1%"

python -c "
import sys, os
Q = chr(34)
d = sys.argv[1]

batch_content = (
    '@echo off\r\n'
    'setlocal\r\n'
    'set TMPFILE=%%TEMP%%\\mp3tag_batch_%%RANDOM%%_%%RANDOM%%.txt\r\n'
    'type nul > ' + Q + '%%TMPFILE%%' + Q + '\r\n'
    'for %%%%F in (%%*) do echo %%%%~F >> ' + Q + '%%TMPFILE%%' + Q + '\r\n'
    'pythonw ' + Q + d + '\\mp3tag_batch.py' + Q + ' --filelist ' + Q + '%%TMPFILE%%' + Q + '\r\n'
    'del ' + Q + '%%TMPFILE%%' + Q + ' 2>nul\r\n'
)
rename_content = (
    '@echo off\r\n'
    'setlocal\r\n'
    'set TMPFILE=%%TEMP%%\\mp3tag_rename_%%RANDOM%%_%%RANDOM%%.txt\r\n'
    'type nul > ' + Q + '%%TMPFILE%%' + Q + '\r\n'
    'for %%%%F in (%%*) do echo %%%%~F >> ' + Q + '%%TMPFILE%%' + Q + '\r\n'
    'pythonw ' + Q + d + '\\mp3tag_rename.py' + Q + ' --filelist ' + Q + '%%TMPFILE%%' + Q + '\r\n'
    'del ' + Q + '%%TMPFILE%%' + Q + ' 2>nul\r\n'
)
open(os.path.join(d, 'run_batch.bat'),  'w', newline='').write(batch_content)
open(os.path.join(d, 'run_rename.bat'), 'w', newline='').write(rename_content)
" "%_D%"

if errorlevel 1 (
    echo ERROR: Failed to write wrapper scripts.
    pause & exit /b 1
)

echo.
echo  =============================================
echo   Installation complete!
echo  =============================================
echo.
echo  Folder: %INSTALL_DIR%
echo.
echo  Configure DoubleCMD:
echo  1. Configuration ^> Options ^> Toolbar
echo  2. Add button "External command":
echo.
echo     BATCH TAG EDITOR:
echo       Command:    cmd
echo       Parameters: /c "%INSTALL_DIR%\run_batch.bat" %%Lm
echo.
echo     RENAME FROM TAGS:
echo       Command:    cmd
echo       Parameters: /c "%INSTALL_DIR%\run_rename.bat" %%Lm
echo.
echo  3. For tag columns (Artist, Album, etc.) use the
echo     audioinfo plugin already included in DoubleCMD:
echo     Configuration ^> Options ^> Files views ^> Columns
echo     Add columns from: Plugins ^> audioinfo
echo.
pause
